const db = require('../../models/db');

async function initializeComplianceTables() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS compliance_snapshots (
      snapshot_date DATE PRIMARY KEY,
      compliance_percentage NUMERIC(5, 2) NOT NULL
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS compliance_reminders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      message TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      read_at TIMESTAMPTZ
    )
  `);
}

async function getStaffComplianceRows(allowedUserIds = null) {
  const userFilter = allowedUserIds
    ? `WHERE id IN (${allowedUserIds.map((_, i) => `$${i + 1}`).join(',')})`
    : '';
  const usersResult = await db.query(
    `SELECT id, name, email, role, created_at FROM users ${userFilter} ORDER BY name`,
    allowedUserIds || []
  );

  // Denominators are now assignment-based (policy_assignments / training_assignments)
  // instead of "every policy"/"target_roles" — a user is only compliant/overdue
  // against the policies and training actually assigned to their role or to them.
  const policyRows = (await db.query(`
    SELECT u.id AS user_id, p.id AS policy_id, p.version AS current_version, p.updated_at AS policy_updated_at,
      (SELECT MIN(pa.created_at) FROM policy_assignments pa
       WHERE pa.policy_id = p.id AND (pa.role_key = u.role OR pa.user_id = u.id)) AS assigned_at,
      (SELECT a.decision FROM acknowledgements a
       WHERE a.policy_id = p.id AND a.user_id = u.id
         AND a.id = (SELECT MAX(a2.id) FROM acknowledgements a2 WHERE a2.policy_id = p.id AND a2.user_id = u.id)) AS decision,
      (SELECT a.version_acknowledged FROM acknowledgements a
       WHERE a.policy_id = p.id AND a.user_id = u.id
         AND a.id = (SELECT MAX(a2.id) FROM acknowledgements a2 WHERE a2.policy_id = p.id AND a2.user_id = u.id)) AS version_acknowledged
    FROM users u
    CROSS JOIN policies p
    WHERE EXISTS (
      SELECT 1 FROM policy_assignments pa
      WHERE pa.policy_id = p.id AND (pa.role_key = u.role OR pa.user_id = u.id)
    )
  `)).rows;

  const trainingRows = (await db.query(`
    SELECT u.id AS user_id, m.id AS module_id, m.created_at AS module_created_at,
      (SELECT MIN(ta.created_at) FROM training_assignments ta
       WHERE ta.module_id = m.id AND (ta.role_key = u.role OR ta.user_id = u.id)) AS assigned_at,
      EXISTS (
        SELECT 1 FROM quiz_attempts qa WHERE qa.module_id = m.id AND qa.user_id = u.id AND qa.passed = TRUE
      ) AS completed
    FROM users u
    CROSS JOIN training_modules m
    WHERE EXISTS (
      SELECT 1 FROM training_assignments ta
      WHERE ta.module_id = m.id AND (ta.role_key = u.role OR ta.user_id = u.id)
    )
  `)).rows;

  const surveyTotalsResult = await db.query('SELECT COUNT(*) AS total FROM survey_questions');
  const totalSurveyQuestions = Number(surveyTotalsResult.rows[0].total);

  const surveyRows = (await db.query(`
    SELECT user_id, COUNT(*) AS answered, MAX(answered_at) AS last_answered_at
    FROM survey_responses
    GROUP BY user_id
  `)).rows;
  const surveyByUser = new Map(surveyRows.map((row) => [String(row.user_id), row]));

  const policiesByUser = new Map();
  for (const row of policyRows) {
    const key = String(row.user_id);
    if (!policiesByUser.has(key)) policiesByUser.set(key, []);
    policiesByUser.get(key).push(row);
  }
  const trainingByUser = new Map();
  for (const row of trainingRows) {
    const key = String(row.user_id);
    if (!trainingByUser.has(key)) trainingByUser.set(key, []);
    trainingByUser.get(key).push(row);
  }

  const dueCutoff = Date.now() - 30 * 24 * 60 * 60 * 1000;
  const isOverdue = (date) => Boolean(date) && new Date(date).getTime() <= dueCutoff;

  return usersResult.rows.map((user) => {
    const key = String(user.id);
    const assignedPolicies = policiesByUser.get(key) || [];
    const assignedTraining = trainingByUser.get(key) || [];
    const survey = surveyByUser.get(key);
    const surveyAnswered = survey ? Number(survey.answered) : 0;
    const surveyComplete = totalSurveyQuestions > 0 && surveyAnswered >= totalSurveyQuestions;

    let acknowledgedPolicies = 0;
    let overdueItems = 0;
    for (const policy of assignedPolicies) {
      const compliant = policy.decision === 'agreed' && Number(policy.version_acknowledged) === Number(policy.current_version);
      if (compliant) {
        acknowledgedPolicies++;
        continue;
      }
      // Effective start of the clock: the latest of when it was assigned,
      // when the user joined, or when the policy itself was last updated.
      const effectiveStart = Math.max(
        Date.parse(policy.assigned_at || user.created_at) || 0,
        Date.parse(user.created_at) || 0,
        Date.parse(policy.policy_updated_at) || 0
      );
      if (isOverdue(effectiveStart)) overdueItems++;
    }

    let completedTraining = 0;
    for (const training of assignedTraining) {
      if (training.completed) {
        completedTraining++;
        continue;
      }
      const effectiveStart = Math.max(
        Date.parse(training.assigned_at || user.created_at) || 0,
        Date.parse(user.created_at) || 0
      );
      if (isOverdue(effectiveStart)) overdueItems++;
    }

    // The security-awareness survey counts as one additional "training" item.
    const totalTraining = assignedTraining.length + (totalSurveyQuestions > 0 ? 1 : 0);
    if (totalSurveyQuestions > 0) {
      if (surveyComplete) {
        completedTraining++;
      } else if (isOverdue(survey ? survey.last_answered_at : user.created_at)) {
        overdueItems++;
      }
    }

    const totalPolicies = assignedPolicies.length;
    const totalItems = totalPolicies + totalTraining;
    const completedItems = acknowledgedPolicies + completedTraining;

    return {
      id: user.id,
      name: user.name,
      email: user.email,
      role: user.role,
      totalPolicies,
      acknowledgedPolicies,
      totalTraining,
      completedTraining,
      pendingItems: totalItems - completedItems,
      overdueItems,
      compliancePercentage: totalItems ? Math.round((completedItems / totalItems) * 100) : 100
    };
  });
}

async function saveComplianceSnapshot(compliancePercentage) {
  await db.query(
    `INSERT INTO compliance_snapshots (snapshot_date, compliance_percentage)
     VALUES (CURRENT_DATE, $1)
     ON CONFLICT (snapshot_date)
     DO UPDATE SET compliance_percentage = EXCLUDED.compliance_percentage`,
    [compliancePercentage]
  );
}

async function getComplianceSnapshots() {
  const result = await db.query(
    `SELECT snapshot_date, compliance_percentage
     FROM compliance_snapshots
     ORDER BY snapshot_date DESC
     LIMIT 90`
  );
  return result.rows.reverse();
}

async function createReminder({ recipientId, createdBy, message }) {
  const result = await db.query(
    `INSERT INTO compliance_reminders (recipient_id, created_by, message)
     VALUES ($1, $2, $3)
     RETURNING id, recipient_id, created_by, message, created_at, read_at`,
    [recipientId, createdBy, message]
  );
  return result.rows[0];
}

async function getRemindersForUser(userId) {
  const result = await db.query(
    `SELECT id, message, created_at, read_at
     FROM compliance_reminders
     WHERE recipient_id = $1
     ORDER BY created_at DESC`,
    [userId]
  );
  return result.rows;
}

module.exports = {
  initializeComplianceTables,
  getStaffComplianceRows,
  saveComplianceSnapshot,
  getComplianceSnapshots,
  createReminder,
  getRemindersForUser
};