const db = require('../../models/db');

async function initializeComplianceTables() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS compliance_snapshots (
      snapshot_date DATE PRIMARY KEY,
      compliance_percentage NUMERIC(5, 2) NOT NULL
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS compliance_reminders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      message TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      read_at TIMESTAMPTZ
    )
  `);
}

async function getStaffComplianceRows() {
  const result = await db.query(`
    SELECT u.id, u.name, u.email, u.role, u.created_at,
      (SELECT COUNT(*) FROM policies) AS total_policies,
      (SELECT COUNT(*) FROM policies p
       WHERE EXISTS (
         SELECT 1 FROM acknowledgements a
         WHERE a.policy_id = p.id AND a.user_id = u.id
           AND a.decision = 'agreed' AND a.version_acknowledged = p.version
           AND a.id = (SELECT MAX(a2.id) FROM acknowledgements a2 WHERE a2.policy_id = p.id AND a2.user_id = u.id)
       )) AS acknowledged_policies,
      (SELECT MIN(p.updated_at) FROM policies p
       WHERE NOT EXISTS (
         SELECT 1 FROM acknowledgements a
         WHERE a.policy_id = p.id AND a.user_id = u.id
           AND a.decision = 'agreed' AND a.version_acknowledged = p.version
           AND a.id = (SELECT MAX(a2.id) FROM acknowledgements a2 WHERE a2.policy_id = p.id AND a2.user_id = u.id)
       )) AS oldest_pending_policy_at,
      (SELECT COUNT(*) FROM survey_questions) AS total_survey_questions,
      (SELECT COUNT(*) FROM survey_responses WHERE user_id = u.id) AS answered_survey_questions,
      (SELECT MAX(answered_at) FROM survey_responses WHERE user_id = u.id) AS last_survey_at,
      (1 + (SELECT COUNT(DISTINCT sq.module_id) FROM survey_questions sq
       JOIN survey_responses sr ON sr.question_id = sq.id
       WHERE sr.user_id = u.id AND sr.answer = sq.weak_answer)
       + (SELECT COUNT(DISTINCT m.id) FROM training_modules m
          WHERE m.target_roles LIKE '%' || u.role || '%'
            AND NOT EXISTS (
              SELECT 1 FROM survey_questions sq
              JOIN survey_responses sr ON sr.question_id = sq.id
              WHERE sr.user_id = u.id AND sr.answer = sq.weak_answer AND sq.module_id = m.id
            ))) AS total_training,
      ((SELECT COUNT(DISTINCT m.id) FROM training_modules m
       WHERE (m.target_roles LIKE '%' || u.role || '%' OR EXISTS (
         SELECT 1 FROM survey_responses sr
         JOIN survey_questions sq ON sq.id = sr.question_id
         WHERE sr.user_id = u.id AND sr.answer = sq.weak_answer AND sq.module_id = m.id
       )) AND EXISTS (
         SELECT 1 FROM quiz_attempts q
         WHERE q.module_id = m.id AND q.user_id = u.id AND q.passed = TRUE
       )) + CASE WHEN (SELECT COUNT(*) FROM survey_responses WHERE user_id = u.id)
           >= (SELECT COUNT(*) FROM survey_questions) AND (SELECT COUNT(*) FROM survey_questions) > 0
         THEN 1 ELSE 0 END) AS completed_training
    FROM users u
    ORDER BY u.name
  `);

  return result.rows.map((row) => {
    const totalPolicies = Number(row.total_policies);
    const acknowledgedPolicies = Number(row.acknowledged_policies);
    const totalTraining = Number(row.total_training);
    const completedTraining = Number(row.completed_training);
    const totalItems = totalPolicies + totalTraining;
    const completedItems = acknowledgedPolicies + completedTraining;
    const surveyComplete = Number(row.total_survey_questions) > 0 &&
      Number(row.answered_survey_questions) >= Number(row.total_survey_questions);
    const requiredModules = Math.max(0, totalTraining - 1);
    const completedModules = Math.max(0, completedTraining - Number(surveyComplete));
    const dueCutoff = Date.now() - 30 * 24 * 60 * 60 * 1000;
    const isOverdue = (date) => date && new Date(date).getTime() <= dueCutoff;
    const overdueItems = Number(isOverdue(row.oldest_pending_policy_at)) +
      Number(!surveyComplete && isOverdue(row.created_at)) +
      (surveyComplete && completedModules < requiredModules && isOverdue(row.last_survey_at)
        ? requiredModules - completedModules
        : 0);

    return {
      id: row.id,
      name: row.name,
      email: row.email,
      role: row.role,
      totalPolicies,
      acknowledgedPolicies,
      totalTraining,
      completedTraining,
      pendingItems: totalItems - completedItems,
      overdueItems,
      compliancePercentage: totalItems ? Math.round((completedItems / totalItems) * 100) : 100
    };
  });
}

async function saveComplianceSnapshot(compliancePercentage) {
  await db.query(
    `INSERT INTO compliance_snapshots (snapshot_date, compliance_percentage)
     VALUES (CURRENT_DATE, $1)
     ON CONFLICT (snapshot_date)
     DO UPDATE SET compliance_percentage = EXCLUDED.compliance_percentage`,
    [compliancePercentage]
  );
}

async function getComplianceSnapshots() {
  const result = await db.query(
    `SELECT snapshot_date, compliance_percentage
     FROM compliance_snapshots
     ORDER BY snapshot_date DESC
     LIMIT 90`
  );
  return result.rows.reverse();
}

async function createReminder({ recipientId, createdBy, message }) {
  const result = await db.query(
    `INSERT INTO compliance_reminders (recipient_id, created_by, message)
     VALUES ($1, $2, $3)
     RETURNING id, recipient_id, created_by, message, created_at, read_at`,
    [recipientId, createdBy, message]
  );
  return result.rows[0];
}

async function getRemindersForUser(userId) {
  const result = await db.query(
    `SELECT id, message, created_at, read_at
     FROM compliance_reminders
     WHERE recipient_id = $1
     ORDER BY created_at DESC`,
    [userId]
  );
  return result.rows;
}

module.exports = {
  initializeComplianceTables,
  getStaffComplianceRows,
  saveComplianceSnapshot,
  getComplianceSnapshots,
  createReminder,
  getRemindersForUser
};