const db = require('../../models/db');

async function initializeIncidentTable() {
  const createTable = `
    CREATE TABLE IF NOT EXISTS incidents (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      incident_type VARCHAR(100) NOT NULL,
      title VARCHAR(255) NOT NULL,
      description TEXT NOT NULL,
      reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      severity VARCHAR(20) NOT NULL DEFAULT 'Medium',
      status VARCHAR(30) NOT NULL DEFAULT 'Open',
      reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
      reviewed_at TIMESTAMPTZ,
      CONSTRAINT incidents_severity_check CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
      CONSTRAINT incidents_status_check CHECK (status IN ('Open', 'Investigating', 'Resolved'))
    )`;

  if (db.dialect === 'sqlite') {
    const existing = await db.query("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'incidents'");
    if (existing.rows.length && /'Pending'|'Under Review'/.test(existing.rows[0].sql)) {
      await db.query('ALTER TABLE incidents RENAME TO incidents_legacy');
      await db.query(createTable);
      await db.query(`
        INSERT INTO incidents (id, user_id, incident_type, title, description, reported_at, severity, status, reviewed_by, reviewed_at)
        SELECT id, user_id, incident_type, title, description, reported_at, 'Medium',
          CASE status WHEN 'Pending' THEN 'Open' WHEN 'Under Review' THEN 'Investigating' ELSE status END,
          reviewed_by, reviewed_at
        FROM incidents_legacy
      `);
      await db.query('DROP TABLE incidents_legacy');
    } else {
      await db.query(createTable);
      const columns = await db.query('PRAGMA table_info(incidents)');
      if (!columns.rows.some((column) => column.name === 'severity')) {
        await db.query("ALTER TABLE incidents ADD COLUMN severity VARCHAR(20) NOT NULL DEFAULT 'Medium'");
      }
    }
    return;
  }

  await db.query(createTable);
  await db.query('ALTER TABLE incidents ADD COLUMN IF NOT EXISTS severity VARCHAR(20) NOT NULL DEFAULT \'Medium\'');
  await db.query('ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_status_check');
  await db.query('ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_severity_check');
  await db.query(`UPDATE incidents SET status = CASE status
    WHEN 'Pending' THEN 'Open' WHEN 'Under Review' THEN 'Investigating' ELSE status END`);
  await db.query("ALTER TABLE incidents ADD CONSTRAINT incidents_status_check CHECK (status IN ('Open', 'Investigating', 'Resolved'))");
  await db.query("ALTER TABLE incidents ADD CONSTRAINT incidents_severity_check CHECK (severity IN ('Low', 'Medium', 'High', 'Critical'))");
}

async function createIncident({
  userId,
  incidentType,
  title,
  description,
  reportedAt,
  severity = 'Medium'
}) {
  const result = await db.query(
    `
      INSERT INTO incidents
      (
        user_id,
        incident_type,
        title,
        description,
        reported_at,
        severity
      )
      VALUES ($1, $2, $3, $4, COALESCE($5, NOW()), $6)
      RETURNING *
    `,
    [
      userId,
      incidentType,
      title,
      description,
      reportedAt || null,
      severity
    ]
  );

  return result.rows[0];
}

async function getAllIncidents() {
  const result = await db.query(`
    SELECT i.*, reporter.name AS reported_by_name, reviewer.name AS reviewed_by_name
    FROM incidents i
    JOIN users reporter ON reporter.id = i.user_id
    LEFT JOIN users reviewer ON reviewer.id = i.reviewed_by
    ORDER BY i.reported_at DESC
  `);

  return result.rows;
}

async function getIncidentsByUser(userId) {
  const result = await db.query(
    `
      SELECT i.*, reporter.name AS reported_by_name, reviewer.name AS reviewed_by_name
      FROM incidents i
      JOIN users reporter ON reporter.id = i.user_id
      LEFT JOIN users reviewer ON reviewer.id = i.reviewed_by
      WHERE i.user_id = $1
      ORDER BY i.reported_at DESC
    `,
    [userId]
  );

  return result.rows;
}

async function updateIncidentStatus(
  incidentId,
  status,
  severity,
  reviewedBy
) {
  const result = await db.query(
    `
      UPDATE incidents
      SET
        status = $1,
        severity = COALESCE($2, severity),
        reviewed_by = $3,
        reviewed_at = NOW()
      WHERE id = $4
      RETURNING *
    `,
    [
      status,
      severity,
      reviewedBy,
      incidentId
    ]
  );

  return result.rows[0];
}

module.exports = {
  initializeIncidentTable,
  createIncident,
  getAllIncidents,
  getIncidentsByUser,
  updateIncidentStatus
};