const db = require('../../models/db');

async function initializeIncidentTable() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS incidents (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      user_id BIGINT NOT NULL,

      incident_type VARCHAR(100) NOT NULL,

      title VARCHAR(255) NOT NULL,

      description TEXT NOT NULL,

      reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

      status VARCHAR(30) NOT NULL DEFAULT 'Pending',

      reviewed_by BIGINT,

      reviewed_at TIMESTAMPTZ,

      CONSTRAINT incidents_status_check
        CHECK (status IN ('Pending', 'Under Review', 'Resolved'))
    )
  `);
}

async function createIncident({
  userId,
  incidentType,
  title,
  description,
  reportedAt
}) {
  const result = await db.query(
    `
      INSERT INTO incidents
      (
        user_id,
        incident_type,
        title,
        description,
        reported_at
      )
      VALUES ($1, $2, $3, $4, COALESCE($5, NOW()))
      RETURNING *
    `,
    [
      userId,
      incidentType,
      title,
      description,
      reportedAt || null
    ]
  );

  return result.rows[0];
}

async function getAllIncidents() {
  const result = await db.query(`
    SELECT
      id,
      user_id,
      incident_type,
      title,
      description,
      reported_at,
      status,
      reviewed_by,
      reviewed_at
    FROM incidents
    ORDER BY reported_at DESC
  `);

  return result.rows;
}

async function getIncidentsByUser(userId) {
  const result = await db.query(
    `
      SELECT
        id,
        user_id,
        incident_type,
        title,
        description,
        reported_at,
        status,
        reviewed_by,
        reviewed_at
      FROM incidents
      WHERE user_id = $1
      ORDER BY reported_at DESC
    `,
    [userId]
  );

  return result.rows;
}

async function updateIncidentStatus(
  incidentId,
  status,
  reviewedBy
) {
  const result = await db.query(
    `
      UPDATE incidents
      SET
        status = $1,
        reviewed_by = $2,
        reviewed_at = NOW()
      WHERE id = $3
      RETURNING *
    `,
    [
      status,
      reviewedBy,
      incidentId
    ]
  );

  return result.rows[0];
}

module.exports = {
  initializeIncidentTable,
  createIncident,
  getAllIncidents,
  getIncidentsByUser,
  updateIncidentStatus
};
