const db = require('../../models/db');

async function initializePolicyTables() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS policies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS acknowledgements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      policy_id BIGINT NOT NULL,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      version_acknowledged INTEGER NOT NULL,
      acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE CASCADE
    )
  `);
}

async function seedDefaultPolicies() {
  const policies = [
    ['Remote Access & AnyDesk Usage Policy', 'Use individual credentials for remote access. Never accept unexpected connection requests, share passwords, or leave a session open. Report suspicious attempts.'],
    ['Password & Credential Handling Policy', 'Use unique passwords. Never store client credentials in personal notes or share them over WhatsApp. Use only approved secure storage and sharing channels.'],
    ['Incident Reporting Procedure', 'Promptly report suspicious requests, lost devices, exposed credentials, and policy violations. Include what happened, when, affected systems, and actions taken.'],
    ['Client Data Handling Guidelines', 'Access only client information needed for assigned work. Do not copy it to personal devices or messaging accounts; report accidental disclosure immediately.']
  ];

  for (const [title, content] of policies) {
    await db.query(
      `INSERT INTO policies (title, content)
       SELECT $1, $2
       WHERE NOT EXISTS (SELECT 1 FROM policies WHERE title = $1)`,
      [title, content]
    );
  }
}

module.exports = { initializePolicyTables, seedDefaultPolicies };
