const db = require('../../models/db');

const GATE_POLICY_TITLES = ['Acceptable Use Policy'];

async function initializePolicyTables() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS policies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  const policyColumns = db.dialect === 'sqlite'
    ? await db.query('PRAGMA table_info(policies)')
    : await db.query(
      'SELECT column_name FROM information_schema.columns WHERE table_name = $1',
      ['policies']
    );
  if (!policyColumns.rows.some((column) => (column.name || column.column_name) === 'requires_gate')) {
    await db.query('ALTER TABLE policies ADD COLUMN requires_gate BOOLEAN NOT NULL DEFAULT FALSE');
    for (const title of GATE_POLICY_TITLES) {
      await db.query('UPDATE policies SET requires_gate = TRUE WHERE title = $1', [title]);
    }
  }

  await db.query(`
    CREATE TABLE IF NOT EXISTS acknowledgements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      policy_id BIGINT NOT NULL,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      version_acknowledged INTEGER NOT NULL,
      acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE CASCADE
    )
  `);

  const acknowledgementColumns = db.dialect === 'sqlite'
    ? await db.query('PRAGMA table_info(acknowledgements)')
    : await db.query(
      'SELECT column_name FROM information_schema.columns WHERE table_name = $1',
      ['acknowledgements']
    );
  const acknowledgementColumnNames = acknowledgementColumns.rows.map((column) => column.name || column.column_name);
  if (!acknowledgementColumnNames.includes('decision')) {
    await db.query("ALTER TABLE acknowledgements ADD COLUMN decision VARCHAR(10) NOT NULL DEFAULT 'agreed'");
  }
  if (!acknowledgementColumnNames.includes('ip_address')) {
    await db.query('ALTER TABLE acknowledgements ADD COLUMN ip_address TEXT');
  }
  if (!acknowledgementColumnNames.includes('user_agent')) {
    await db.query('ALTER TABLE acknowledgements ADD COLUMN user_agent TEXT');
  }

  await db.query('CREATE INDEX IF NOT EXISTS idx_ack_user_policy ON acknowledgements (user_id, policy_id, id)');
}

async function seedDefaultPolicies() {
  const policies = [
    ['Acceptable Use Policy', 'Use SinglePoint and company systems only for authorized business activity. Every person must use their own account and must never share credentials. Passwords must be at least 12 characters; the system stores passwords as bcrypt hashes. Sessions expire after 30 minutes of inactivity. Acknowledge current policies, complete required training, and report suspected security incidents promptly. Required policies and training become overdue after 30 days. Training quizzes require a score of at least 70% to pass. Staff may access their own records; managers may review team compliance and incidents; admins manage accounts, policies, and training.', true],
    ['Remote Access & AnyDesk Usage Policy', 'Use individual credentials for remote access. Never accept unexpected connection requests, share passwords, or leave a session open. Report suspicious attempts.', false],
    ['Password & Credential Handling Policy', 'Use unique passwords. Never store client credentials in personal notes or share them over WhatsApp. Use only approved secure storage and sharing channels.', false],
    ['Incident Reporting Procedure', 'Promptly report suspicious requests, lost devices, exposed credentials, and policy violations. Include what happened, when, affected systems, and actions taken.', false],
    ['Client Data Handling Guidelines', 'Access only client information needed for assigned work. Do not copy it to personal devices or messaging accounts; report accidental disclosure immediately.', false]
  ];

  for (const [title, content, requiresGate] of policies) {
    await db.query(
      `INSERT INTO policies (title, content, requires_gate)
       SELECT $1, $2, $3
       WHERE NOT EXISTS (SELECT 1 FROM policies WHERE title = $1)`,
      [title, content, requiresGate]
    );
  }
}

// Gate policies the user has NOT currently agreed to (latest row for that
// policy, by MAX(id), must be decision='agreed' at the current version).
async function getPendingGatePolicies(userId) {
  const result = await db.query(
    `SELECT p.id, p.title, p.content, p.version FROM policies p
     WHERE p.requires_gate = TRUE AND NOT EXISTS (
       SELECT 1 FROM acknowledgements a
       WHERE a.policy_id = p.id AND a.user_id = $1 AND a.decision = 'agreed' AND a.version_acknowledged = p.version
         AND a.id = (SELECT MAX(a2.id) FROM acknowledgements a2 WHERE a2.policy_id = p.id AND a2.user_id = $1)
     )
     ORDER BY p.id`,
    [userId]
  );
  return result.rows;
}

async function getPolicyById(id) {
  const result = await db.query('SELECT * FROM policies WHERE id = $1', [id]);
  return result.rows[0] || null;
}

async function getLatestAcknowledgement(policyId, userId) {
  const result = await db.query(
    `SELECT * FROM acknowledgements a
     WHERE a.policy_id = $1 AND a.user_id = $2
     ORDER BY a.id DESC LIMIT 1`,
    [policyId, userId]
  );
  return result.rows[0] || null;
}

async function insertAcknowledgement({ policyId, userId, versionAcknowledged, decision, ipAddress, userAgent }) {
  const result = await db.query(
    `INSERT INTO acknowledgements (policy_id, user_id, version_acknowledged, decision, ip_address, user_agent)
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING *`,
    [policyId, userId, versionAcknowledged, decision, ipAddress || null, userAgent || null]
  );
  return result.rows[0];
}

async function getAcknowledgementHistory(policyId) {
  const result = await db.query(
    `SELECT a.id, a.user_id, u.name AS user_name, u.email, a.version_acknowledged, a.decision, a.acknowledged_at, a.ip_address
     FROM acknowledgements a
     JOIN users u ON u.id = a.user_id
     WHERE a.policy_id = $1
     ORDER BY a.id DESC`,
    [policyId]
  );
  return result.rows;
}

module.exports = {
  initializePolicyTables,
  seedDefaultPolicies,
  getPendingGatePolicies,
  getPolicyById,
  getLatestAcknowledgement,
  insertAcknowledgement,
  getAcknowledgementHistory
};
