const db = require('../../models/db');

async function initializePolicyTables() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS policies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS acknowledgements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      policy_id BIGINT NOT NULL,
      user_id BIGINT NOT NULL,
      version_acknowledged INTEGER NOT NULL,
      acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      FOREIGN KEY (policy_id) REFERENCES policies(id) ON DELETE CASCADE
    )
  `);
}

module.exports = { initializePolicyTables };
