const db = require('../../models/db');

async function initializeTrainingTables() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS training_modules (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      category TEXT NOT NULL,
      duration_min INTEGER NOT NULL DEFAULT 10,
      content TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS survey_questions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      question TEXT NOT NULL,
      weak_answer TEXT NOT NULL CHECK (weak_answer IN ('yes','no')),
      module_id BIGINT NOT NULL REFERENCES training_modules(id) ON DELETE CASCADE
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS survey_responses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      question_id BIGINT NOT NULL REFERENCES survey_questions(id) ON DELETE CASCADE,
      answer TEXT NOT NULL CHECK (answer IN ('yes','no')),
      answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (user_id, question_id)
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS quiz_questions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      module_id BIGINT NOT NULL REFERENCES training_modules(id) ON DELETE CASCADE,
      question TEXT NOT NULL,
      options JSONB NOT NULL,
      correct_index INTEGER NOT NULL
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS quiz_attempts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      module_id BIGINT NOT NULL REFERENCES training_modules(id) ON DELETE CASCADE,
      score INTEGER NOT NULL,
      total INTEGER NOT NULL,
      passed BOOLEAN NOT NULL,
      attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  const columns = db.dialect === 'sqlite'
    ? await db.query('PRAGMA table_info(training_modules)')
    : await db.query(
      'SELECT column_name FROM information_schema.columns WHERE table_name = $1',
      ['training_modules']
    );
  const hasUpdatedAt = columns.rows.some((column) => (column.name || column.column_name) === 'updated_at');
  if (!hasUpdatedAt) {
    await db.query('ALTER TABLE training_modules ADD COLUMN updated_at TIMESTAMPTZ');
  }
  await db.query('UPDATE training_modules SET updated_at = created_at WHERE updated_at IS NULL');

  await seedTrainingData();
}

async function seedTrainingData() {
  const existing = await db.query('SELECT COUNT(*)::int AS n FROM training_modules');
  if (existing.rows[0].n > 0) return;

  const modules = [
    ['Phishing & Social Engineering', 'Threat Awareness', 12,
     'Learn to spot suspicious messages, fake requests and pressure tactics. Never act on unexpected requests without verifying them.'],
    ['Password & Credential Safety', 'Credential Management', 8,
     'Never share logins, never store client passwords in personal notes, and never send credentials over WhatsApp.'],
    ['Safe Remote Access Practices', 'Access Control', 10,
     'Use your own individual login, close every remote session when finished, and decline unexpected connection requests.'],
    ['How to Report an Incident', 'Incident Management', 6,
     'Report anything suspicious through the in-app incident form straight away. Do not just mention it in chat.']
  ];

  const ids = [];
  for (const m of modules) {
    const r = await db.query(
      `INSERT INTO training_modules (title, category, duration_min, content)
       VALUES ($1,$2,$3,$4) RETURNING id`, m);
    ids.push(r.rows[0].id);
  }
  const [phish, pass, remote, report] = ids;

  const survey = [
    ['Have you ever shared a login with a coworker?', 'yes', pass],
    ['Do you keep client passwords in personal notes or chats?', 'yes', pass],
    ['Do you close remote sessions after finishing?', 'no', remote],
    ['Do you check who is connecting before accepting a remote request?', 'no', remote],
    ['Do you open links in unexpected emails or messages?', 'yes', phish],
    ['Do you report suspicious things through a proper channel?', 'no', report]
  ];
  for (const s of survey) {
    await db.query(
      'INSERT INTO survey_questions (question, weak_answer, module_id) VALUES ($1,$2,$3)', s);
  }

  const quiz = [
    [phish, 'You receive an AnyDesk connection request from a client at 11 PM. What do you do?',
      ['Accept it, clients can connect anytime', 'Accept it and monitor what they do',
       'Decline and report it through the incident reporting system', 'Ask a colleague on WhatsApp what to do'], 2],
    [phish, 'An email asks you to urgently confirm your password via a link. What is this most likely?',
      ['A routine IT check', 'A phishing attempt', 'A client request', 'A system update'], 1],
    [phish, 'What should you do with a suspicious message?',
      ['Delete it and say nothing', 'Forward it to everyone', 'Report it via the incident form', 'Reply to ask who sent it'], 2],
    [pass, 'A client POS password needs to reach a colleague. What is correct?',
      ['Send it on WhatsApp', 'Write it in your personal notes', 'Use the approved secure channel', 'Email it in plain text'], 2],
    [pass, 'Is it acceptable to share your login with a coworker?',
      ['Yes, if they are in a hurry', 'Yes, if they are a manager', 'Only on weekends', 'No, never'], 3],
    [pass, 'Where should work credentials NOT be stored?',
      ['An approved password manager', 'Personal notes or chat apps', 'An encrypted vault', 'Nowhere insecure'], 1],
    [remote, 'When you finish a remote session you should:',
      ['Leave it open for later', 'Close and terminate it immediately', 'Minimise the window', 'Tell a colleague'], 1],
    [remote, 'Which login should you use for remote access?',
      ['The shared developer login', 'Your own individual credentials', 'A colleague\'s login', 'No login'], 1],
    [remote, 'A connection request arrives outside business hours. You should:',
      ['Accept it', 'Decline and report it', 'Ignore it', 'Accept if the client ID looks familiar'], 1],
    [report, 'Where should a suspicious incident be reported?',
      ['A WhatsApp group', 'In passing to a colleague', 'The in-app incident report form', 'Nowhere'], 2],
    [report, 'When should you report a lost work device?',
      ['Next week', 'Only if data was lost', 'Immediately', 'Never'], 2],
    [report, 'Who receives your incident report?',
      ['Nobody', 'The Admin (CEO)', 'Your client', 'Social media'], 1]
  ];
  for (const q of quiz) {
    await db.query(
      `INSERT INTO quiz_questions (module_id, question, options, correct_index)
       VALUES ($1,$2,$3::jsonb,$4)`,
      [q[0], q[1], JSON.stringify(q[2]), q[3]]);
  }
}

async function createTrainingModule({ title, category, durationMin, content }) {
  const result = await db.query(
    `INSERT INTO training_modules (title, category, duration_min, content)
     VALUES ($1, $2, $3, $4)
     RETURNING id, title, category, duration_min, content, created_at, updated_at`,
    [title, category, durationMin, content]
  );
  return result.rows[0];
}

async function updateTrainingModule(id, { title, category, durationMin, content }) {
  const result = await db.query(
    `UPDATE training_modules
     SET title = $1, category = $2, duration_min = $3, content = $4, updated_at = NOW()
     WHERE id = $5
     RETURNING id, title, category, duration_min, content, created_at, updated_at`,
    [title, category, durationMin, content, id]
  );
  return result.rows[0] || null;
}

async function createQuizQuestion(moduleId, { question, options, correctIndex }) {
  const result = await db.query(
    `INSERT INTO quiz_questions (module_id, question, options, correct_index)
     VALUES ($1, $2, $3::jsonb, $4)
     RETURNING id, module_id, question, options`,
    [moduleId, question, JSON.stringify(options), correctIndex]
  );
  return result.rows[0];
}

async function updateQuizQuestion(moduleId, questionId, { question, options, correctIndex }) {
  const result = await db.query(
    `UPDATE quiz_questions
     SET question = $1, options = $2::jsonb, correct_index = $3
     WHERE module_id = $4 AND id = $5
     RETURNING id, module_id, question, options`,
    [question, JSON.stringify(options), correctIndex, moduleId, questionId]
  );
  return result.rows[0] || null;
}

module.exports = {
  initializeTrainingTables,
  createTrainingModule,
  updateTrainingModule,
  createQuizQuestion,
  updateQuizQuestion
};