const db = require('../../models/db');

async function initializeUserTable() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      role VARCHAR(20) NOT NULL DEFAULT 'staff',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CONSTRAINT users_role_check CHECK (role IN ('admin', 'manager', 'staff'))
    )
  `);

  const columns = db.dialect === 'sqlite'
    ? await db.query('PRAGMA table_info(users)')
    : await db.query(
      'SELECT column_name FROM information_schema.columns WHERE table_name = $1',
      ['users']
    );
  if (!columns.rows.some((column) => (column.name || column.column_name) === 'is_active')) {
    await db.query('ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE');
  }

  await db.query(`
    CREATE TABLE IF NOT EXISTS auth_sessions (
      session_id TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TIMESTAMPTZ NOT NULL,
      revoked_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await db.query(`
    CREATE TABLE IF NOT EXISTS login_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      action VARCHAR(30) NOT NULL,
      occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ip_address TEXT,
      user_agent TEXT
    )
  `);
}

async function createUser({ name, email, passwordHash, role }) {
  const result = await db.query(
    `INSERT INTO users (name, email, password_hash, role)
     VALUES ($1, $2, $3, $4)
    RETURNING id, name, email, role, is_active, created_at`,
    [name, email, passwordHash, role]
  );
  return result.rows[0];
}

// Includes password_hash — only used internally by the login controller.
// Never send this row straight back to the client.
async function findUserByEmail(email) {
  const result = await db.query('SELECT * FROM users WHERE email = $1', [email]);
  return result.rows[0] || null;
}

async function findUserById(id) {
  const result = await db.query(
    'SELECT id, name, email, role, is_active, created_at FROM users WHERE id = $1',
    [id]
  );
  return result.rows[0] || null;
}

async function getAllUsers() {
  const result = await db.query(
    'SELECT id, name, email, role, is_active, created_at FROM users ORDER BY created_at DESC'
  );
  return result.rows;
}

async function updateUserRole(id, role) {
  const result = await db.query(
    'UPDATE users SET role = $1 WHERE id = $2 RETURNING id, name, email, role, is_active, created_at',
    [role, id]
  );
  return result.rows[0] || null;
}

async function changePassword(id, passwordHash) {
  const result = await db.query(
    'UPDATE users SET password_hash = $1 WHERE id = $2 RETURNING id',
    [passwordHash, id]
  );
  return result.rows[0] || null;
}

async function setUserActive(id, isActive) {
  const result = await db.query(
    'UPDATE users SET is_active = $1 WHERE id = $2 RETURNING id, name, email, role, is_active, created_at',
    [isActive, id]
  );
  return result.rows[0] || null;
}

async function getActiveAdminCount() {
  const result = await db.query("SELECT COUNT(*) AS count FROM users WHERE role = 'admin' AND is_active = TRUE");
  return Number(result.rows[0].count);
}

async function getLoginEvents(limit = 100) {
  const result = await db.query(
    `SELECT e.id, e.user_id, u.name AS user_name, e.action, e.occurred_at, e.ip_address
     FROM login_events e LEFT JOIN users u ON u.id = e.user_id
     ORDER BY e.occurred_at DESC LIMIT $1`,
    [limit]
  );
  return result.rows;
}

async function createAuthSession(sessionId, userId, expiresAt) {
  await db.query(
    'INSERT INTO auth_sessions (session_id, user_id, expires_at) VALUES ($1, $2, $3)',
    [sessionId, userId, expiresAt]
  );
}

async function findAuthSession(sessionId, userId) {
  const result = await db.query(
    `SELECT session_id FROM auth_sessions
     WHERE session_id = $1 AND user_id = $2 AND revoked_at IS NULL AND expires_at > $3`,
    [sessionId, userId, new Date().toISOString()]
  );
  return result.rows[0] || null;
}

async function refreshAuthSession(sessionId, expiresAt) {
  await db.query('UPDATE auth_sessions SET expires_at = $1 WHERE session_id = $2', [expiresAt, sessionId]);
}

async function revokeAuthSession(sessionId) {
  await db.query(
    'UPDATE auth_sessions SET revoked_at = $1 WHERE session_id = $2 AND revoked_at IS NULL',
    [new Date().toISOString(), sessionId]
  );
}

async function revokeUserSessions(userId) {
  await db.query(
    'UPDATE auth_sessions SET revoked_at = $1 WHERE user_id = $2 AND revoked_at IS NULL',
    [new Date().toISOString(), userId]
  );
}

async function recordLoginEvent({ userId = null, action, ipAddress, userAgent }) {
  await db.query(
    `INSERT INTO login_events (user_id, action, ip_address, user_agent)
     VALUES ($1, $2, $3, $4)`,
    [userId, action, ipAddress || null, userAgent || null]
  );
}

module.exports = {
  initializeUserTable,
  createUser,
  findUserByEmail,
  findUserById,
  getAllUsers,
  updateUserRole,
  changePassword,
  setUserActive,
  getActiveAdminCount,
  getLoginEvents,
  createAuthSession,
  findAuthSession,
  refreshAuthSession,
  revokeAuthSession,
  revokeUserSessions,
  recordLoginEvent
};
